apiVersion: v1
kind: ConfigMap
metadata:
  name: backstage-config
  labels:
    {{- include "backstage.labels" . | nindent 4 }}
data:
  app-config.yaml: |
{{ .Files.Get .Values.config.appConfigPath | indent 4 }}
